### PR TITLE
fix: check obi data in e2e tests

### LINKED ISSUE #40: flake test in "Scheduler e2e test only use score crd"
from https://github.com/kube-arbiter/arbiter/actions/runs/3316798009/jobs/5479060916 and pre github action running, we can see there is a flake test in `Scheduler e2e test only use score crd [It] schedule a simple busybox pod`

code: https://github.com/kube-arbiter/arbiter/blob/main/tests/e2e/scheduler_test.go#L138

### PR DESCRIPTION
**Pull request by Abirdcfly**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
1. metrics like `kube_node_status_allocatable_cpu_cores` and `kube_node_status_allocatable_cpu_cores` are marked as DEPRECATED.
2. metrics like `kube_node_spec_taint` will has no data when there is no taint in cluster.
3. The value (`.status.metrics.*[*].records.*.value`) is not a number and cant be summed does not means does not mean that it is wrong, perhaps the value is original raw data from prometheus.
#### Which issue(s) this PR fixes:

Fixes #40 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: tests/install-infra.sh [hunk 1]
```diff
@@ -94,7 +94,15 @@ function test_obi {
 		for i in $(seq 1 2); do
 			[ $(kubectl get obi ${name} -n ${ARBITER_NS} -oyaml | grep 'timestamp' | awk '{print NR}' | tail -n1) -ge 2 ] && s=0 && break || s=$? && sleep 10
 		done
-		if [ $s -ne 0 ]; then
+
+		# check data valid
+		sum=$(kubectl get obi ${name} -n ${ARBITER_NS} -o jsonpath="{.status.metrics.*[*].records.*.value}" | awk 'BEGIN{sum=0} {for(i=1;i<=NF;i++)sum+=$i} END{print(sum)}')
+		if [ $sum -eq 0 ]; then
+			# The value is not a number and cant be summed does not means does not mean that it is wrong, perhaps the value is original raw data from prometheus
```
Comment (nkwangleiGIT) [inline tests/install-infra.sh:101]: The value is not a number and cant be summed does not means does not mean that it is wrong
=> The value might not be a number and  summed, but it maybe not wrong as the value maybe original raw data from prometheus.

Comment (Abirdcfly) [reply tests/install-infra.sh]: Done
